version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2-php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
      - redis

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2-queue
    volumes:
      - ./src:/var/www/html
    command: php yii queue/listen --verbose --color
    depends_on:
      - php
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgis/postgis:15-3.4
    container_name: yii2-postgres
    environment:
      POSTGRES_DB: mpdb
      POSTGRES_USER: mpuser
      POSTGRES_PASSWORD: mppassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: yii2-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis:7
    container_name: yii2-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  pgdata:
  pgadmin-data:
  redis-data:
