version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2-php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:15
    container_name: yii2-postgres
    environment:
      POSTGRES_DB: projectapp
      POSTGRES_USER: projectuser
      POSTGRES_PASSWORD: dfg3r4343dsd3Gd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: yii2-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
